platform :ios, '9.0'

target 'WoonPatroon' do
  
  use_frameworks!

  pod 'SwiftyJSON', '3.1.4'
  pod 'Charts', '3.0.3'

  target 'WoonPatroon-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  end

  target 'WoonPatroonTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
	target.build_configurations.each do |config|
	  config.build_settings['SWIFT_VERSION'] = '3.0'
        end
     end
  end

end

target 'WoonPatroon-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!


end
